#!/usr/bin/env bash

PROJECT_ROOT=`cd "$(dirname ${0})"/../ && pwd`

pushd $PROJECT_ROOT/games >/dev/null


killprodserver() {
  ps xww -o pid,ppid,user,command 2>&1 | grep 'otree prodserver' | grep -v grep | awk '{ print $1 }' | xargs kill
}

killprodserver >/dev/null 2>&1

popd >/dev/null
