#!/usr/bin/env bash

if [ ! "$(hostname)" = "scmotree" ]; then
  echo Host is not scmotree. Exiting.
  exit 1
fi

PROJECT_ROOT="$( cd "$(dirname "${0}")/.." >/dev/null 2>&1 ; pwd -P )"
cd "${PROJECT_ROOT}"

# Ensure environment is setup, virtual env is created, deps installed, etc
${PROJECT_ROOT}/scripts/setup

# activate virtualenv
[ -z "$VIRTUAL_ENV" ] && source ./venv/bin/activate

[ -f "requirements-prod.txt" ] && pip install -r "requirements-prod.txt"


cd games

mkdir -p "${PWD}/logs"

# Well, we should kill any prodserver jobs that currently exist... there can only be one prodserver (unless we're in the cloud & have distributed databases with all the fancy bells & whistles)
[ -x ${PROJECT_ROOT}/scripts/kill_prodserver ] && ${PROJECT_ROOT}/scripts/kill_prodserver

BROADCAST_IP=$(ifconfig | grep broadcast | grep -Po 'inet \K[\d.]+')

OTREE_PRODUCTION=1 \
  OTREE_AUTH_LEVEL=${OTREE_AUTH_LEVEL} \
  OTREE_ADMIN_USERNAME=${OTREE_ADMIN_USERNAME} \
  OTREE_ADMIN_PASSWORD=${OTREE_ADMIN_PASSWORD} \
  SERPAPI_KEY=${SERPAPI_KEY} \
  otree prodserver "$BROADCAST_IP:8000" > "${PWD}/logs/prodserver.log" 2>&1 & disown

