#!/usr/bin/env bash

PROJECT_ROOT="$( cd "$(dirname "${0}")/.." >/dev/null 2>&1 ; pwd -P )"
cd "${PROJECT_ROOT}"

# add project directory to python sys.path - allows importing modules from the local project directory
export PYTHONPATH=${PROJECT_ROOT}

# setup virtualenv & basic package management dependencies
if [ ! -d ${PROJECT_ROOT}/venv ]; then
    command -v pyenv &> /dev/null
    if [ $? -eq 0 ]; then
        py39="$(pyenv versions --bare | grep '3.9' | sort -nr | head -1 &> /dev/null)"
        if [ $? -eq 0 ]; then
            pyenv local "${py39}"
        fi
    fi
    python3 -m venv ${PROJECT_ROOT}/venv
fi

# activate virtualenv
source ${PROJECT_ROOT}/venv/bin/activate

## configure git pull & merge options
git config pull.rebase false
git config merge.ff true

# install dev dependencies
if [ -f ${PROJECT_ROOT}/requirements-dev.txt ]; then
    pip install -U -r ${PROJECT_ROOT}/requirements-dev.txt
fi

# install prod dependencies (exact)
if [ -f ${PROJECT_ROOT}/requirements-prod.txt ]; then
    pip install -r ${PROJECT_ROOT}/requirements-prod.txt
fi
